DROP TABLE IF EXISTS TBL_EMPLOYEES;
  
CREATE TABLE TBL_EMPLOYEES (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  first_name VARCHAR(250) NOT NULL,
  last_name VARCHAR(250) NOT NULL,
  email VARCHAR(250) DEFAULT NULL
);


DROP TABLE IF EXISTS CUSTOMER;

CREATE TABLE CUSTOMER (
id INT AUTO_INCREMENT  PRIMARY KEY,
name VARCHAR(20), 
age NUMBER, address VARCHAR(20),
salary NUMBER
);  


DROP TABLE IF EXISTS STUDENT;

CREATE TABLE STUDENT(
id INT AUTO_INCREMENT  PRIMARY KEY,
name VARCHAR(20), 
age NUMBER, 
address VARCHAR(20),
email VARCHAR(40)
);  
